export const TRIPS_DATA = [
  {
    id: 1,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 2,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 3,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 4,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 5,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 6,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 7,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 8,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 9,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 10,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
  {
    id: 11,
    name: "Cascada X",
    description: "Descriere excursie",
    difficulty: "BEGGINER",
    latitude: 50,
    longitude: 50,
    categoryId: null,
  },
];
